#!/usr/bin/env bash

TO_WINDOW="$1"
PASS_WINDOW="$(xdotool getactivewindow)"

set -euo pipefail
IFS=$'\n\t'

cd "$HOME/.password-store" || exit 1
PASSFILE="$(tree -Ffi | grep '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | fzf)"

if [ -z "$PASSFILE" ]; then
	exit 0
fi

PASSDATA=$(pass "$PASSFILE")

MENU=($(echo "$PASSDATA" | tail -n +2 | sed 's/\:.*//' ))
MENU+=("DISPLAY")
MENU+=("PASSWORD")

RESP=$(printf "%s\n" "${MENU[@]}" | fzf --tac)

if [ "$RESP" = "DISPLAY" ]; then
    echo "$PASSDATA"
    sleep 30
    exit 0
fi

O="$(echo "$PASSDATA" | head -n 1)"
if [ "$RESP" != "PASSWORD" ]; then
    O="$(echo "$PASSDATA" | awk -F ':' -v VAR="$RESP" '$1==VAR { Z=substr($0, length($1) + 2); gsub(/^[ \t]+|[ \t]+$/, "", Z); print Z }')"
fi

xdotool windowminimize "$PASS_WINDOW"
xdotool windowactivate "$TO_WINDOW"
sleep 0.5
xdotool type "$O"
echo Done | aosd_cat -p 4 -n "Anonymous Pro 99" -R lime
