#!/usr/bin/env bash


function ldotool {
    ydotool type ""
    if [ $? eq 0 ]; then
        ydotool "$@"
    else
        xdotool "$@"
    fi
    return $?
}


cd $HOME/.password-store
PASSFILE=$(tree -Ffi | grep '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | fzf)

if [ -z "$PASSFILE" ]; then
	exit 0
fi

PASSDATA="$(pass $PASSFILE)"
USRNAME="$(echo "$PASSDATA" | egrep -i "username:|user:" | head -1 | cut -d' ' -f2-)"
PASS="$(echo "$PASSDATA" | head -n 1)"
URL="$(echo $PASSDATA | grep url: | cut -d' ' -f2-)"

RESP=$(cat <<EOF | fzf
Autotype
Username
Password
OTP
URL
EOF
);

CURRENT_WORKSPACE=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused == true)' | jq -r .name)
if [ "$CURRENT_WORKSPACE" -eq 9 ]; then
    swaymsg move container to workspace 8
else
    swaymsg move container to workspace 9
fi

case "$RESP" in
	Autotype)
		ldotool type "$USRNAME" && ldotool key Tab && ldotool type "$PASS" && ldotool key Enter
		;;
	Username)
		ldotool type "$USRNAME"
		;;
	Password)
		ldotool type "$PASS"
		;;
	OTP)
		ldotool type "$(pass otp $PASSFILE)"
		;;
	URL)
		ldotool type "$URL"
		;;
	*)
		exit 1
esac
